name: Rassegna Telpress (08–12:59 ogni 15')

on:
  schedule:
    - cron: "*/15 * * * *"   # GitHub Actions usa UTC; lo script ha già il guard Europe/Rome
  workflow_dispatch:

concurrency:
  group: telpress-rassegna
  cancel-in-progress: true

jobs:
  run:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4

      - uses: actions/setup-python@v5
        with:
          python-version: "3.11"

      - uses: actions/cache@v4
        with:
          path: ~/.cache/pip
          key: pip-${{ runner.os }}-${{ hashFiles('**/requirements.txt') }}
          restore-keys: |
            pip-${{ runner.os }}-

      - name: Install dependencies
        run: pip install -r requirements.txt

      # Guard orario extra (opzionale ma utile): 08:00–12:59 Europe/Rome per i run schedulati
      - name: Time window guard (Europe/Rome 08:00–12:59)
        if: ${{ github.event_name == 'schedule' }}
        run: |
          python - <<'PY'
          from datetime import datetime
          from zoneinfo import ZoneInfo
          now = datetime.now(ZoneInfo("Europe/Rome"))
          hhmm = now.hour*100 + now.minute
          print(f"Ora locale: {now.strftime('%Y-%m-%d %H:%M')}")
          if not (800 <= hhmm < 1300):
              print("Fuori finestra (08:00–12:59). Esco senza fare nulla.")
              raise SystemExit(0)
          print("Dentro la finestra. Procedo.")
          PY

      - name: Run Telpress Bot
        env:
          # --- Lettura Telpress (restano invariati) ---
          SENDER_FILTER:       ${{ secrets.SENDER_FILTER }}
          SUBJECT_PREFIX:      ${{ secrets.SUBJECT_PREFIX }}
          DRIVE_FOLDER_ID:     ${{ secrets.DRIVE_FOLDER_ID }}
          TIMEZONE:            Europe/Rome
          SERVICE_ACCOUNT_FILE: service_account.json
          SERVICE_ACCOUNT_JSON: ${{ secrets.SERVICE_ACCOUNT_JSON }}
          CLIENT_SECRET_JSON:   ${{ secrets.CLIENT_SECRET_JSON }}
          GOOGLE_TOKEN_JSON:    ${{ secrets.GOOGLE_TOKEN_JSON }}

          # --- SOLO invio notifica via Aruba (nuovi) ---
          SMTP_HOST: smtps.aruba.it
          SMTP_PORT: "465"
          SMTP_SECURE: ssl
          SMTP_USER: news@ancepiemonte.it
          SMTP_PASS: ${{ secrets.SMTP_PASS }}
          SMTP_SENDER_NAME: "ANCe Piemonte News"
          # SMTP_REPLY_TO: comunicazioni@ancepiemonte.it   # opzionale

          # Destinatari / contenuto (metti in secret se vuoi)
          NOTIFY_TO: ${{ secrets.NOTIFY_TO }}              # oppure "lista@dominio.it,a@b.it"
          # NOTIFY_SUBJECT: "Rassegna stampa {date_it} caricata"
          # NOTIFY_BODY: |
          #   Buongiorno,
          #   la rassegna del {date_it} è stata caricata automaticamente
          #   https://ancepiemonte.streamlit.app/
          #   Cordiali saluti
        run: |
          printf '%s' "$SERVICE_ACCOUNT_JSON" > service_account.json
          printf '%s' "$CLIENT_SECRET_JSON"  > client_secret.json
          python telpress_email_to_drive.py --quiet


