name: Rassegna Telpress

on:
  schedule:
    - cron: "30 6 * * *"   # 08:30 Europa/Roma (06:30 UTC)
  workflow_dispatch:

jobs:
  run:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repo
        uses: actions/checkout@v3

      - name: Set up Python
        uses: actions/setup-python@v4
        with:
          python-version: "3.11"

      - name: Install dependencies
        run: pip install -r requirements.txt

      - name: Run Telpress Bot
        env:
          # Config app
          SENDER_FILTER: ${{ secrets.SENDER_FILTER }}
          SUBJECT_PREFIX: ${{ secrets.SUBJECT_PREFIX }}
          DRIVE_FOLDER_ID: ${{ secrets.DRIVE_FOLDER_ID }}
          TIMEZONE: Europe/Rome
          SERVICE_ACCOUNT_FILE: service_account.json

          # Credenziali
          SERVICE_ACCOUNT_JSON: ${{ secrets.SERVICE_ACCOUNT_JSON }}
          CLIENT_SECRET_JSON: ${{ secrets.CLIENT_SECRET_JSON }}
          GOOGLE_TOKEN_JSON: ${{ secrets.GOOGLE_TOKEN_JSON }}
        run: |
          # Ricrea i JSON necessari
          echo "$SERVICE_ACCOUNT_JSON" > service_account.json
          echo "$CLIENT_SECRET_JSON" > client_secret.json

          # Esegui: ultima rassegna (finestra ultimi 3 giorni)
          python telpress_email_to_drive.py --days 3
